### ISSUE TITLE
Implement functional flows metrics

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#40]
The data can be found here

**Comment by postfalk** [comment]
@kklausmeyer I took a first look at the functional flow data on the N:/ drive and I need much more guidance on the proposed data model and what data we should serve. Do you you think we could find time to look at it together?

**Comment by kklausmeyer** [comment]
Yes of course. I think we can knock it out in a 30 min meeting but we should schedule for 1 hour to be safe. I’ll send you a meeting request

On Dec 11, 2019, at 12:04 PM, Falk Schuetzenmeister <notifications@github.com> wrote:

﻿

@kklausmeyer<https://github.com/kklausmeyer> I took a first look at the functional flow data on the N:/ drive and I need much more guidance on the proposed data model and what data we should serve. Do you you think we could find time to look at it together?

**Comment by postfalk** [comment]
Thanks, and I hope you are not annoyed by this incremental approach. Falk


Falk Schuetzenmeister | Geospatial Software Engineer

The Nature Conservancy

t. 510.604.8010

s. 201 Mission St., Floor 4, San Francisco, CA 94105

e. falk.schuetzenmeister@tnc.org<mailto:falk.schuetzenmeister@tnc.org> | w. nature.org/california



 [cid:cf42856e-6116-4489-bd8d-67561a4dd25a]



________________________________

**Comment by kklausmeyer** [comment]
Of course I'm not annoyed-  the data structure is not clear and we need some time to figure out how best to serve it up to the intended audience

**Comment by kklausmeyer** [comment]
The raw data are in two locations:

1) Functional flow metric predictions for all years: N:\WATER_Program\projects\FunctionalFlows\data\FunctionalFlow_data_20191118\Data\NHD FFM predictions (25 files)
2) Selected functional flow metric predictions by water year type: N:\WATER_Program\projects\FunctionalFlows\data\FunctionalFlow_data_20191118\Data\NHD FFM predictions by WYT (16 files)

We would like to post all of these data on the rivers API.  The files in location 1 have the same schema as the files in location 2, except they are missing the "WYT" field (water year type).  Please add "WYT" to the files in location 1, and set the value for all rows to "All years".  

If you would like to store the data in a more "long" format, you could convert the p10, p25, p50, p75 and p90 fields to two fields- "percentile" and "value".  

The only thing that might be good to add is a "units" field that would be populated based on the values in the "FFM" field, but we will have to ask Julie what the units are (e.g., days, cfs, etc). We could also provide this info in the API metadata.

**Comment by postfalk** [comment]
@kklausmeyer I have a few questions:

1. You probably already provided the guide to the abbreviations but I cannot find them. What does e.g. DS_Mag_50 mean?

2. There are less variables in the by_wyt folder, does that mean that some measures don't make sense for different water years?

3. What is percentile value we would most likely put in the graphics? Would it make sense to display one of the values by default with the option to request percentiles?

**Comment by postfalk** [comment]
@kklausmeyer 4. Are there other sources than models in the data set? Could we avoid to store the word model a million times?

**Comment by postfalk** [comment]
@kklausmeyer 5. I am allowed to round the values to two digits after the decimal point. Please!

**Comment by kklausmeyer** [comment]
Yes, there are some other sousrces like "Observed" in the data so best to keep "model" for now.  I think you can round to two digits after the decimal point.  No problem with me.

**Comment by kklausmeyer** [comment]
> The raw data are in two locations:
> 
> 1. Functional flow metric predictions for all years: N:\WATER_Program\projects\FunctionalFlows\data\FunctionalFlow_data_20191118\Data\NHD FFM predictions (25 files)
> 2. Selected functional flow metric predictions by water year type: N:\WATER_Program\projects\FunctionalFlows\data\FunctionalFlow_data_20191118\Data\NHD FFM predictions by WYT (16 files)
> 
> We would like to post all of these data on the rivers API. The files in location 1 have the same schema as the files in location 2, except they are missing the "WYT" field (water year type). Please add "WYT" to the files in location 1, and set the value for all rows to "All years".
> 
> If you would like to store the data in a more "long" format, you could convert the p10, p25, p50, p75 and p90 fields to two fields- "percentile" and "value".
> 
> The only thing that might be good to add is a "units" field that would be populated based on the values in the "FFM" field, but we will have to ask Julie what the units are (e.g., days, cfs, etc). We could also provide this info in the API metadata.

**Comment by kklausmeyer** [comment]
> @kklausmeyer I have a few questions:
> 
> 1. You probably already provided the guide to the abbreviations but I cannot find them. What does e.g. DS_Mag_50 mean?
The description for each code is here:  "N:\WATER_Program\projects\FunctionalFlows\data\FunctionalFlow_data_20191118\Functional Flow Metrics List and Definitions.xlsx"

> 2. There are less variables in the by_wyt folder, does that mean that some measures don't make sense for different water years?
Yes, I think some variables are not calculated by wyt.  Seems there wasn't enough data to calculate by water year type.

> 3. What is percentile value we would most likely put in the graphics? Would it make sense to display one of the values by default with the option to request percentiles?
I think 50th percentile is likely the default value.

**Comment by postfalk** [comment]
Almost done. Needs to be deployed.
