### ISSUE TITLE
Discrepancy in # of stream segments between natural flows and functional flow metrics

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#41]
Hi @kklausmeyer, there is a difference in the # of stream segment in nf (139916) and ffm (141600). Should I remove the segments not present in nf? They will not be accessible through the map but would appear during the download

**Comment by kklausmeyer** [comment]
Could you give me a sample of the COMIDs that are in ffm but not nf?  I would like to check out the attributes in the NHD Plus dataset.

**Comment by postfalk** [comment]
Yes, I have to run this check over a lot of Comids first. Falk


Falk Schuetzenmeister | Geospatial Software Engineer

The Nature Conservancy

t. 510.604.8010

s. 201 Mission St., Floor 4, San Francisco, CA 94105

e. falk.schuetzenmeister@tnc.org<mailto:falk.schuetzenmeister@tnc.org> | w. nature.org/california



 [cid:6814942b-e565-4baa-966e-1926cf1edd2a]



________________________________

**Comment by kklausmeyer** [comment]
I think we can close this - there appears to be different methods used to generate the different ffm estimates, and they used different sets of COMIDs to make the estimates.  At this point, we can just publish the data we were given and direct any questions to Ted Grantham about methods.

**Comment by postfalk** [comment]
great!
