### ISSUE TITLE
Should I standardize observed vs. estimated terminology?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#42]
In natural flows we have "estimated" vs. "observed" in FFM we have "model" vs. "obs"

**Comment by kklausmeyer** [comment]
Good catch!  In this case, I think the ffm "observed" is a misleading term, since it is not the same thing as "observed in nf.  Let me check with Julie on this.  But for now my proposed term for ffm would be "inferred from reference sites" rather than "observed"

**Comment by kklausmeyer** [comment]
In an email on 1/10/2020 Julie confirmed that we should use the term "inferred" to replace "obs" for the ffm data.

**Comment by postfalk** [comment]
Ok. I guess there will be a lot of explaining in the documentation ;)
