### ISSUE TITLE
FFM data questions to settle

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#44]
@jkzimmerman Could you please provide the units for the ffm variables. Thank you

**Comment by kklausmeyer** [comment]
Hi Falk-  you can find the units for each metric in this lookup table:

"N:\WATER_Program\projects\FunctionalFlows\data\FunctionalFlow_data_20191118\Functional Flow Metrics List and Definitions.xlsx"

**Comment by postfalk** [comment]
The ffm names are not the same as in the data I received. Sorry for making fun of random capitalization people seem to love (Maybe they could learn German where Capitalization is much more common e.g. in all Nouns)

```
flOw_mETricsCode      api_data

FA_Mag                fa_mag
FA_Tim                fa_tim
FA_Dur                                    MISSING

Wet_BFL_Mag_10        wet_bfl_mag_10
Wet_BFL_Mag_50        wet_bfl_mag_50
Wet_Tim               wet_tim
Wet_BFL_Dur           wet_bfl_dur

Peak_2                                    MISSING
Peak_5                                    MISSING
Peak_10                peak_10
Peak_Dur_2                                MISSING
Peak_Dur_5                                MISSING
Peak_Dur_10                               MISSING
Peak_Fre_2                                MISSING
Peak_Fre_5                                MISSING
Peak_Fre_10                               MISSING
?                      peak_20            NOT IN UNIT TABLE
?                      peak_50            NOT IN UNIT TABLE

SP_Mag                 sp_mag
SP_Tim                 sp_tim
SP_Dur                 sp_dur
SP_ROC                                    MISSING

DS_Mag_50              ds_mag_50
DS_Mag_90              ds_mag_90
DS_Tim                 ds_tim
DS_Dur_WS              ds_dur_ws
```

Is it correct that the Peakflowvalues are not exactly seasonal even though it seems likely that they occur in the Regenzeit?

**Comment by postfalk** [comment]
I have updated the last post and confirm that the missing values are still missing. @kklausmeyer Could you please have a look at the N: drive whether you can find the data?

**Comment by kklausmeyer** [comment]
Hi @postfalk - from the list it looks like you have only ingested the predcitions by water year type (WYT) so far.  If you add the files in this folder (N:\WATER_Program\projects\FunctionalFlows\data\FunctionalFlow_data_20191118\Data\NHD FFM predictions) you will see all the missing variables should be included.

The files in the folder above do not include the field "WYT" like the other values do.  Please add this field to the data when you ingest them, and give all the data points a value of "All years" so the schema is consistent with the data you already ingested.

**Comment by postfalk** [comment]
Got it. This is due inconsistent naming in the files containing the variables it is only called Peak_20 instead of Peak_Dur_20. The filename has the right clue, I hope. Naming is hard.

**Comment by postfalk** [comment]
The discussion went far of the original issue but I am to lazy to open a new one at this point. 

Is it correct that peak_fre_ ... and peak_dur ... exist only for about half the stream segments?

**Comment by kklausmeyer** [comment]
Good observation Falk-  I believe that is correct, because the source of these data are the "obs" or "inferred" data, not from the random forest models.  I think they estimated these variables based on 11 groups of river types, and they were not able to assign all the comid segmets to one of these 11 groups.  Thanks for noting the different in the numbers and we will have to account for this in our visualization.
