### ISSUE TITLE
Missing FFM metrics?

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/rivers-stream#46]
Hey Falk, I'm comparing the FFM API output to the [functional flow metrics list and definitions](https://docs.google.com/spreadsheets/d/1dgcjD0hsO95EDhR1oBbK-2mMw6971p6qKO5cVjss8-g/edit#gid=0), and If you query without specifying which FFM's to return (e.g. [https://flow-api.codefornature.org/v2/ffm/?comids=10000042](https://flow-api.codefornature.org/v2/ffm/?comids=10000042)), there appear to be some missing metrics. Some of the codes that are present in the google sheet but not in returned by the API are:

- fa_dur (fall pulse flow - duration)
- peak_dur_2 (peak flow - duration - 2 year recurrence interval)
- peak_dur_5 (peak flow - duration - 5 year recurrence interval)
- peak_dur_10 (peak flow - duration - 2 year recurrence interval)
- peak_fre_2 (peak flow - frequency - 2 year recurrence interval)
- peak_fre_5 (peak flow - frequency - 5 year recurrence interval)
- peak_fre_10 (peak flow - frequency - 10 year recurrence interval)

Maybe I'm doing something wrong?

**Comment by postfalk** [comment]
That is correct, the metrics don't have been calculated for every stream segment. However, according to Kirk they also reviewing the data since their seem to be also duplicate keys with divergent values. Close this for now.
