### ISSUE TITLE
Load observed functional flow data and alteration metrics to ffm api

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#48]
Hi Falk-

As we discussed in our team meetings, we would like to append some source="observed" data into into the functional flow api.  I had to do quite a bit of wrangling of the data to remove some errors from the data Nick Santos and Ryan Peak sent me, but I think it is in good shape so far.  I may have to make minor changes to the data, but I am hoping the schema will be stable.  I will attached the data to this issue.

The data should fit the existing schema with the following additional fields needed:

1. gage_id:  This is a numeric field similar to COMID that gives the USGS ID for each gage location.
2.observed_years:  If you can think of a better name for this, that is fine, but basically I want to indicate the count of years with enough observed data to calculate a given functional flow metric (e.g., dry season magnitude).  Some gages have partial records so even if the gage was active for a given year, there may not be enough data to calculate the functional flow metric.  This value ranges from 0 to 128 and is an integer.
3. alteration:  This is a text field that describes the type of alteration based on the observed data.  There are also entries if there is not enough data present to make a determination, or if there are no predictions of the ffm for a given stream segment.  

The primary complicating factor here is that >20 of the COMIDs have multiple stream gages.  In some cases, (e.g. comid = 342483), the two stream gages are located on different side of a reservoir and the observed alteration for one gage is different than that measured at another gage.  I think we simplified this for the natural flows data by selection one gage to display per stream segment, but I'm wondering if we should allow the user to choose which gage to display in the popup?  Given our short timeline, I'm happy to go with whatever is the easiest, but I just want it to be clear what the user is seeing in these mulitple gage situations.

**Comment by kklausmeyer** [comment]
Here are the alteration data:
[usgs_altered_ffc_percentiles_Updated_Schema_20200410.zip](https://github.com/tnc-ca-geo/rivers-stream/files/4463502/usgs_altered_ffc_percentiles_Updated_Schema_20200410.zip)

**Comment by postfalk** [comment]
Quick question. Is that the **complete** data for each stream segment that has the additional data? OR do we need to merge the data with the other data for the segments?

**Comment by kklausmeyer** [comment]
That is additional “observed” data so we need to append it to the existing data. In excel, I would paste the rows at the end of the existing data table and make sure the columns match up.

On Apr 13, 2020, at 5:15 PM, Falk Schuetzenmeister <notifications@github.com> wrote:

﻿

Quick question. Is that the complete data for each stream segment that has the additional data? OR do we need to merge the data with the other data for the segments?

**Comment by postfalk** [comment]
Done ead8ffe. Thanks @kklausmeyer for the data wrangling.

**Comment by postfalk** [comment]
@kklausmeyer Please spot check

**Comment by kklausmeyer** [comment]
Spot check complete and the observed data appears to be returned correctly.  (e.g., https://flow-api.codefornature.org/v2/ffm/?comids=20216276).  Thanks @postfalk !
