### ISSUE TITLE
Query requirements

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#51]
@kklausmeyer I merged and cleaned the data. In the next step, I have to implement a few changes to the API. 

Are there query requirements for the time being in order to filter by the new metrics. I guess just querying by ```sources=observed``` should be sufficient

**Comment by kklausmeyer** [comment]
Yes- that would be fine to do `sources=observed`.  I imagine users will also query by the "alteration" field, so it would be good to be able to get all of the data where` alteration=likely_altered_high`, for example.

**Comment by postfalk** [comment]
Thx
