### ISSUE TITLE
Remove incorrect data from API

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#54]
Ted included some data that shouldn't be in the API for the functional flows database so we need to remove it.  Here is what needs to be removed:

ffms in [peak_10, peak_2, peak_5] AND wyts in [dry, moderate, wet]

(Note, we need to KEEP the data associated with ffms in [peak_10, peak_2, peak_5] AND wyts = all)

**Comment by postfalk** [comment]
Are peak_dur_10, peak_dur_2, peak_dur_5, peak_fre_10, peak_fre_2, and peak_fre_5 ok or do they need to be removed as well?

**Comment by kklausmeyer** [comment]
They should be fine-  they should only have data for the WYT = "all", which we want to keep. Basically we want to remove any value associated with peak functional flow data for water year types dry, moderate, and wet, but keep all the values associated with peak functional flow data for water year type "all".

**Comment by postfalk** [comment]
Ok working on this. Will take awhile to upload. Internet is very sluggish today.

**Comment by postfalk** [comment]
That should be done. @kklausmeyer, please evaluate the result and close out. Thx

**Comment by kklausmeyer** [comment]
Confirmed by spot checking various COMIDs in the app and in the API.  It all looks good!  Thank you @postfalk
