### ISSUE TITLE
Update observed functional flows

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#55]

**Comment by postfalk** [comment]
@kklausmeyer and @jkzimmerman please let me know when new data is vetted and formatted.

**Comment by postfalk** [comment]
Is that what we are talking about in #59, close as duplicate if correct. thx

**Comment by kklausmeyer** [comment]
These are two separate issues.  #59 is to update the peak flow estimates, while this issue is to update the observed flows.  Actually, this issue is contingent on #59 being completed first along with some other code updates happening by other teams.  So we are in a waiting pattern for this.

**Comment by postfalk** [comment]
@kklausmeyer  What is the status on this?

**Comment by kklausmeyer** [comment]
I'm getting close, but I have to work on some strategy maps first.  I hope to have them to you by friday 12/4.

**Comment by postfalk** [comment]
I think that is duplicated by #66 now. Close.
