### ISSUE TITLE
Explore options to store versions of the monthly and functional flow databases

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#57]
We anticipate making both minor and major changes to the natural flow databases overtime.  It would be great if there was a way to archive the dataset with version numbers.  However, I know the data are huge and paying for storage will add up over time.  Please let me know what you think the annual cost per version stored will be.  I would be happy to work on the documentation and numbering of the various versions.

**Comment by postfalk** [comment]
Is the goal to leave the versions published (e.g. as download) or just available for us?

If we were to store to S3 active storage would be $0.023 per GB or about $2 per month and version. In glacier which means recoverable but not immediately accessible it could be as low as $0.004 per GB.

**Comment by kklausmeyer** [comment]
The goal would be for external people to be able to download it, but glacier might work.  Do you have an estimate of the size of a zipped version of the database in GB?

**Comment by postfalk** [comment]
FFM is about 173Mbyte (not a big deal)
Monthly is about 42Gbyte which is a little bit unwieldy

**Comment by kklausmeyer** [comment]
Oh sorry-  I see that you already included a monthly charge in Active Storage.  Lets move it to active storage for now, and then we can move to glacier after a year or so.  I would like to keep the FFM and Monthly separate with different version numbers.  The Monthly flow data is currently V2.0.0 since I don't think we have made any changes to what the USGS gave us as their V2.  I'm working with Ted on the FFM version number, but I think it is V1.0.0.  Ted sent me some updates to the peak flow data, so we can call that version V1.1.0.  Sound good?

**Comment by postfalk** [comment]
See #60
