### ISSUE TITLE
Remove monthly and FFM data associated with COMIDs that are entirely contained in the legal delta

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#58]
Due to issues with divergences, the functional flows team does not feel comfortable publishing flow estimates in the legal delta.  We decided to keep these areas in the map, but color them with the light purple color that indicates "no flow data" that we currently use for the canals and other streams without flow data.  Here is a shapefile for the legal delta:   https://atlas-dwr.opendata.arcgis.com/datasets/57b02f8a5e77465f902376dbd9522585_0.  Please let me know if you would like me to send you a list of COMIDs or if you want to do the analysis yourself.  Ted and Julie would like to archive a version of the data set with the detla data intact, but for the current version accessible via the API and web interface, the flow estimates in the delta should be deleted.

**Comment by postfalk** [comment]
Oh no, I let the worms out ... yes a list would be great.

**Comment by postfalk** [comment]
More questions on this one:
- Are we removing only FFM or all flow data?

**Comment by kklausmeyer** [comment]
Hi Falk-  Ted, Julie, and I agreed we should remove all flow data (FFM and monthly) for the following reasons:
1. Divergences-  the Delta is full of divergences, and we know that the flow estimates are putting all the flow down both sides of the divergence, so it is likely we are overestimating natural flows in most of the channels
2. Drainage area size-  the training data for the monthly flows and FFM is based on reference gages and we don't have any reference gages in huge watersheds.  The Delta includes most of the area of the state as a drainage area, so we felt our estimates are more uncertain in this area.

**Comment by kklausmeyer** [comment]
Here is a [list of COMIDs](https://tnc.box.com/s/gqrtc9jewmnxi9mnphr49p9szc0mza5q) that are fully within the legal delta, as mapped by DWR available on this [website](https://data.cnra.ca.gov/dataset/legal-delta-boundary1). I only selected flow lines that are completely within the legal delta boundaries. I also made one minor change to one COMID (1897416) on the San Joaquin River because this one is on the border of the legal delta and it has a stream gage.  I chose to remove this COMID from the list so that we will maintain the natural flows estimates for it so we can compare to the gage because it doesn't have the issues with too many divergences.

**Comment by kklausmeyer** [comment]
One more thing on symbology.  We would like to keep the Delta flowlines in the webapp and with the thicker line widths for the stream segments that have high estimated flows, and just turn them all to the light pink color.  I'm concerned that if we remove the estimated flow data, the line widths will all become skinny regardless of the stream size.  Hopefully they can stay wide since that has a nice cartographic effect.

**Comment by postfalk** [comment]
Please confirm! Are we removing monthly data as well?

**Comment by kklausmeyer** [comment]
Yes- correct.  We would like to remove the data associated with the Delta and the Colorado river for both Monthly AND FFM datasets.

**Comment by postfalk** [comment]
Done 8dde191
