### ISSUE TITLE
Update Peak Flow FFM estimates based on new data from Ted

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#59]
I will provide you with the new data in the correct format shortly.  Just adding this so I don't forget

**Comment by kklausmeyer** [comment]
Ok-  here are the new data to add to the FFM database.  The schema should be the same.

https://tnc.box.com/s/zzx18fb1gd42qc7jfc88j2tyt2wbm618

Before you append these data, please delete all records that meet the following conditions:
ffm in ["peak_dur_2", "peak_dur_5", "peak_fre_2", "peak_fre_5", "peak_2", "peak_5", "peak_10"]
AND
source in ["model", "inferred"]

NOTE-  you will be deleting more records than you add, because the V1.0 data had peak_2, peak_5, and peak_10 metrics by water year type (which was incorrect).  The new replacement data only has one value and it doesn't vary by water year type.

**Comment by kklausmeyer** [comment]
Here is a screenshot of the new data you can use to check for ['comid'] == 22597421 in the database after the updates:
![image](https://user-images.githubusercontent.com/11560493/98589317-f4e97c00-2281-11eb-84f8-7f8962cbcb2d.png)

**Comment by postfalk** [comment]
Is that modeled (aka estimated) data?

**Comment by kklausmeyer** [comment]
Yes-  it is modeled data.  Some of the peak flow metrics are "inferred", including peak_dur_2, peak_dur_5, peak_fre_2, peak_fre_5.  But we are treating the "inferred" data the same as the modeled data.

**Comment by postfalk** [comment]
Do we still need the "inferred field"?

**Comment by kklausmeyer** [comment]
The inferred data has the value "inferred" in the "source" field.  I didn't think we had a separate "inferred" field.

**Comment by postfalk** [comment]
Quick question. Is the swap complete in the sense that I could delete the old peak values across the entire data set or is it more a patch where I have to check every single time. Which metrics are we changing. In short:

- If I remove metrics according the above list, can I also remove the old values?
- What are those?

It would safe a lot of time if we could go about this that way.

**Comment by kklausmeyer** [comment]
Hi Falk-  yes the swap is complete.  The old peak flow values are considered "incorrect" for those ffm components listed above:

ffm in ["peak_dur_2", "peak_dur_5", "peak_fre_2", "peak_fre_5", "peak_2", "peak_5", "peak_10"]
AND
source in ["model", "inferred"]

So you can delete the full records including the old values, and replace them with the new records with the new values in the CSV

**Comment by postfalk** [comment]
Great, will do that in a minute. Falk

________________________________

**Comment by postfalk** [comment]
Please check whether changes are made correctly. I tested for the example and I think they are. Let me know when it is the case.

Also found this line for observed. Does it make sense?

22597421,peak_10,all,197.2,197.2,197.2,197.2,197.2,cfs,observed,10255800,33.0,indeterminate

**Comment by postfalk** [comment]
I will move on with removing legal delta and Colorado river if confirmed.

**Comment by kklausmeyer** [comment]
Awesome-  I just did a series of spot checks on all variables and they all checked out.  Thanks so much for your diligence on this!

For COMID 22597421, I think the observed values all being the same is ok, because it is a peak flow estimate and observed data.  Since the time range doesn't have that many 10 year recurrance interval floods, it has the same value for p10 through p90.  Thanks for flagging this, but I think it is fine in this case.

**Comment by kklausmeyer** [comment]
I'll close this issue and let the team know the peak flow estimates have been updated.
