### ISSUE TITLE
Create archive of natural flows data versions for public access.

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#60]
Based on issue #57 , create an S3 active storage archive for the monthly and FFM databases.  Here is the changelog:

Monthly Flows:
V2.0.0:  

- Created by the USGS and completed on 12/18/2016.

- Includes monthly flow estimates from 1950-2015 for COMIDs limited to the political boundaries of California

V2.0.1(not complete yet):

- Updated by The Nature Conservancy in November, 2020.

- Removed data from the legal delta because of the many divergences and large drainage areas associated with the flowlines in the legal delta.

FFM:
V1.0.0:

- Modeled data created by Ted Grantham and the California Environmental Flows Framework Technical Team (https://ceff.sf.ucdavis.edu/about) on 11/19/2019.

- Observed flows at gage locations added based on analyses conducted by Nick Santos and Ryan Peek for reference gages on 4/18/2020 and for altered gages on 2/18/2020.

V1.0.1

- Removed negative flow values that arose from rounding very small negative numbers.

V1.1.0 (not complete yet):

- Updated with new peak flow metrics (for peak_dur_2, peak_dur_5, peak_fre_2, and peak_fre_5) provided by Ted Grantham on 10/31/2020.

- Removed data from the legal delta because of the many divergences and large drainage areas associated with the flowlines in the legal delta.

**Comment by postfalk** [comment]
Where should that go in the grant schema of things. I will prepare the download links for later placement.

**Comment by postfalk** [comment]
https://rivers.codefornature.org/data/ffm_v1.0.0.zip
https://rivers.codefornature.org/data/ffm_v1.0.1.zip (null corrected)

We should discuss, how to pack the monthly data which seems to be too big for single zip files.

**Comment by kklausmeyer** [comment]
This is great Falk!  I'll update the version numbers in the comment above to reflect V1.0.1.  As to where the changelog should go, I think at the end of the [Data](https://rivers.codefornature.org/#/data) page we can add a section about data changes and versions.  Or perhaps at the top of the page.

For big zip files, I'm not sure.  Does 7-zip do a better job?  We could put it in 7-zip format since that is a free download.

**Comment by kklausmeyer** [comment]
Hi Falk-  I just downloaded ffm_v1.0.1.zip and it is taking me 10 mins to unzip the file because each comid has a separate .csv file.  Could you make one large .csv with all COMIDs instead of multiple .csvs?

**Comment by postfalk** [comment]
I could. The problem would be that it would be to large to be opened in Excel. Falk

________________________________

**Comment by kklausmeyer** [comment]
That is ok-  I think most people that would be interested in an earlier version of the data will be able to open large .csv files.

Also, can you add a header to the file with the column names, like the downloads have?

**Comment by kklausmeyer** [comment]
I moved the changelog to a [google doc](https://docs.google.com/document/d/1C-QZi4K00x3yZ_SRpSKx_cAY9I29cjb_-jnT7_MpSCc/edit?usp=sharing) here for easy updates.  Feel free to edit it if you like.

**Comment by postfalk** [comment]
@kklausmeyer Ok. I can do it. But in the big picture we might think of a better way to release that data in a coherent form, maybe a more tabular form. Even better would be to put it in a real data repository.

**Comment by kklausmeyer** [comment]
Yes I like the idea of versioning the data on the API as well, so you could access older versions via the API.  I'm pretty agnostic about the location and type of data storage, as long as the annual costs are relatively low.

**Comment by kklausmeyer** [comment]
Hi Falk-  I checked the data for the V1.0.1 link (https://rivers.codefornature.org/data/ffm_v1.0.1.zip) and it still has the null problem.  But this is the version I downloaded 10 days ago.  Have you updated it since then?

**Comment by postfalk** [comment]
I might delay this work a little for time reasons. I don't think is essential for the next release of the frontend

**Comment by kklausmeyer** [comment]
Hi Falk- I wanted to check in on this issue.  Were you able to explore the versioning archive options a bit more?  I'd like to include links to the old versions, but we only have v1.0.0 and v1.0.1 right now.   I would also like to have the older versions available in one .csv file rather than one .csv for each COMID.  Thank you!

**Comment by postfalk** [comment]
Here is FFM data in a single file 

https://rivers.codefornature.org/data/ffm-final-v1.2.1.zip
