### ISSUE TITLE
Remove FFM and Monthly Flow data on river segments associated with Colorado River

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#62]
The lower Colorado River has a drainage area that is much larger than any of the reference gages, so the FFM and montly flow estimates are suspect.  Ted and Julie suggest we remove the data associated with these flowlines.  This CSV includes all the COMIDs for the Colorado River mainstem that forms the border of CA:  

https://tnc.box.com/s/23xu8n19wxnymyzgv1rhjstk5twv68bt

I generated this file by selecting all comids in the NHDPlus V2 dataset for region 15 with a  "TotDASqKM" > 400,000.  This includes the lower colorado river to the ocean, as well as any local divergences.  

As with the Delta, we want to keep the flow lines in the webmap, but have no data returned in the map or the API.

**Comment by kklausmeyer** [comment]
Please complete work on issue #59 first before doing this one, because the new data from Ted may include some data for the Colorado River and we want it removed.

**Comment by postfalk** [comment]
Done 8dde191
