### ISSUE TITLE
Should we reduce ffm precision to a sane amount of digits?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#64]
Maybe not in that iteration but it seems like a good idea and would reduce the size of the data set quite a bit

**Comment by kklausmeyer** [comment]
Yes- I think we should and other users have requested this as well.  Perhaps round everything to the nearest hundreths?

**Comment by postfalk** [comment]
I have to look into this. I think the best way would be something like this:

1238408 --> 1240000
.37443  --> 0.374

**Comment by kklausmeyer** [comment]
It might be good to get Ted and @jkzimmerman  opinion on this since we are becoming the defacto storage location of the FFM data and I want to make sure they agree with our plans.

**Comment by postfalk** [comment]
Ok. I am not in a hurry, actually somewhat stretched thin.

**Comment by kklausmeyer** [comment]
Ok we got approval from Ted and Darren to display the FFM data to three significant digits.  I'll leave it up to you if you want to include this edit in the next version or to create a new version.

**Comment by postfalk** [comment]
That has been implemented throughout. Slows the processing pipeline down considerably. We might think of a better approach the next time around.
