### ISSUE TITLE
River symbology incorrect

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#65]
Hi Falk-  The current version of the rivers symbology is correctly showing the Delta, but there are some new issues with stream segments that have observed FFM data.  They should be displayed with a salmon color, but they have a purple color.  Here are some examples:  COMID: 2852705 (should have the color of "Observed monthly and functional flow")
![image](https://user-images.githubusercontent.com/11560493/101079704-ad8e9c80-355c-11eb-820f-faff85c9355d.png)

COMID: 7968113 (should have the color of "Observed monthly and functional flow")
![image](https://user-images.githubusercontent.com/11560493/101079805-d020b580-355c-11eb-8930-a710c1d322c4.png)

**Comment by postfalk** [comment]
I consider that solved. @kklausmeyer please double-check and close. Thank you.

**Comment by kklausmeyer** [comment]
This looks great to me-  thank you!
