### ISSUE TITLE
Create and new version of the FFM database by updating observed FFM data

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#66]
Hi Falk-  Here is my last update before I head out on paternity leave.  Please update the current version to the ffm database (v1.1.1) by deleting all of the data where:
`source == 'observed'`

Please update the schema of the entire database to include two new integer fields:
`observed_year_start
observed_year_end`

Please append all records from this[ .csv file in box ](https://tnc.box.com/s/k0i20076lh7w2wx6h5l22r9sbichpp7h) to the new database, which I would like to call v1.2.0.  

When you are done please update the symbology of the rivers layer to reflect the new stream segments with observed FFM data.  See issue #65 .

Thank you!

**Comment by postfalk** [comment]
Ok. Will do not sure whether by the end of week but before Christmas. Falk

________________________________

**Comment by postfalk** [comment]
@kklausmeyer Quick question whenever you get to it. Is it correct that the peak flow update we did earlier #59 is obsolete or does it still need to be applied when we start from the original data?

**Comment by postfalk** [comment]
Please confirm: ffm_observed_20201208.csv has only 13966 records

Is that all observations or additional new observations?

Background: I am trying to reconstruct the dataset from its original sources.

**Comment by kklausmeyer** [comment]
> @kklausmeyer Quick question whenever you get to it. Is it correct that the peak flow update we did earlier #59 is obsolete or does it still need to be applied when we start from the original data?

Hi @postfalk- the peak flow update from #59 does still need to be applied when starting from original data.  Thanks for asking!

**Comment by kklausmeyer** [comment]
> Please confirm: ffm_observed_20201208.csv has only 13966 records
> 
> Is that all observations or additional new observations?
> 
> Background: I am trying to reconstruct the dataset from its original sources.

@postfalk - confirmed-  ffm_observed_20201208.csv does have only 13966 records.  This represents all valid observations.  Previous versions of the observed data may have had information for other stream gages, but I did an extensive review and found many gages were not on streams, but on pipelines or canals, so I removed them since alteration from the "natural" flow in a pipeline doesn't make any sense.  ffm_observed_20201208.csv represents the latest and greatest version of observed flow data and replaces all earlier versions of observed data (source == 'observed').

**Comment by kklausmeyer** [comment]
Please hold off on completing this task-  I need to generate a new .csv file with the observed data.  The schema and the number of rows will be the same, but some of the alteration assessment values will be different.

**Comment by kklausmeyer** [comment]
Here is the latest version of the observed data (ffm_observed_20210121.csv).  IT takes care of the records with less than 15 years of data, and converts those to "not enough data" alteration type.
https://tnc.box.com/s/cm43skgssgvtlrdb2ctqxlzw11gkxup2

**Comment by postfalk** [comment]
@kklausmeyer data is up for thorough review. Please close out or file new issues for problems.

Thank you, Falk

**Comment by kklausmeyer** [comment]
Initial check looks good!  Will do a more thorough check later today

**Comment by kklausmeyer** [comment]
Hi Falk-  It looks like you might be using an older dataset.  In my comment 28 days ago I gave a link to the updated dataset ([ffm_observed_20210121.csv](https://tnc.box.com/s/cm43skgssgvtlrdb2ctqxlzw11gkxup2)).  It looks like you are using the original dataset in this issue ([ffm_observed_20201208.csv](https://tnc.box.com/s/k0i20076lh7w2wx6h5l22r9sbichpp7h)).  Please delete the current FFM observed data, and replace with the data in the ffm_observed_20210121.csv file.  

Here are some places to test:
22524845, ds_tim. observed - should be "not_enough_observed_data", but you have it as "likely_unaltered"
20247268, ds_dur_ws, observed - - should be "not_enough_observed_data", but you have it as "likely_unaltered"

Please note that this should not affect the symbology of the river layers-  it will just affect what is displayed in the pop-up boxes.











-- | --

**Comment by postfalk** [comment]
That is not a big problem. Will be up tomorrow. Sorry for losing track. falk

________________________________

**Comment by postfalk** [comment]
Damn, did not see that you provided a 2021 version. Ok. I can reprocess this I did read your comment but did not pay attention to the numbers in the filename. Sorry, Falk

**Comment by kklausmeyer** [comment]
Yes I noticed the dates look very similar on a quick glance.  Thank you so much for your help on this!  The new data are really interesting to explore-

**Comment by postfalk** [comment]
I guess that is solved. Could you please check. It is pretty late.

**Comment by postfalk** [comment]
Again - hopefully, really - ready for review.

**Comment by kklausmeyer** [comment]
Spot check is looking good!  I think we are set with this one.  I'll work with Natty to update the interface and version numbers.
