### ISSUE TITLE
Add flag for comid records with questionable flow estimates in FFM and monthly database 

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#67]
This is not a top priority but something we should do in the spring to flag comids that have questionable flow estimates, like the canals on Mill Creek and the lower Little Shasta River.  The simpliest flag would be a binary field that would be True if the estimates are questionable, or False if not.  More complicated would be an integer field that would link to a lookup table that indicates the reason for the why the estimates are questionable.  More complicated still would be a text field that you could write out long form comments about why the estimates are questionable and reach specific information.  

Just a placeholder for now, but I would like to work on this in the spring of 2021.

**Comment by postfalk** [comment]
Please clarify status of this issue? Thx

**Comment by kklausmeyer** [comment]
This is a placeholder for work to be done in the next major release, but not urgent right now.
