### ISSUE TITLE
Publish MVP results (Version 2.1.0) to API

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#70]
The current API only has data from 1950-2015, so we would like to add in the data from 2016-2021.   The data to publish are here:

N:\Projects\CA_FWA\projects\UnimparedFlows\data\modeled_and_observed_flow *
*Edit on 10/26/21 - I included observed data in these files so you can upload modeled and observed monthly data in one step.  The observed data only exist for the subset of comids with gages.

Note that the data are organized by year and month, with the following naming convention:  flow_YYYY_MM.csv with all the COMIDs in one file.  This is to allow a monthly update of the data- every month we will add a new file with the flow estimates for the previous month.  

We want to publish the data in the following files:
flow_2016_01.csv
flow_2016_02.csv
flow_2016_03.csv
.
.
.
flow_2021_06.csv
flow_2021_07.csv
flow_2021_08.csv
flow_2021_09.csv

Note that the folder contains files with data prior to 2016-  please don't publish those, since I only generated them to compare to the existing USGS model. 

The data in the files are in the same structure as the data you can download from the Natural Flows tool now, so hopefully it will be easier to publish:

![image](https://user-images.githubusercontent.com/11560493/135896172-f7d3ec2d-8e63-46f7-b501-cc34c820751a.png)

**Comment by postfalk** [comment]
Is the observed data part of this?

**Comment by kklausmeyer** [comment]
Yes I wrote some new code to include the observed data in these files.

**Comment by postfalk** [comment]
There are fewer comids in your data than in the original one 134647 vs. 139914 even though the difference seems to be relatively small.

Missing examples are 10000042 and 10000688. Did you include the few stream segments outside of the California drainage? Or did you already remove the stream segments we are not displaying in the application.

Or is there something wrong with my extraction scripts?

**Comment by kklausmeyer** [comment]
Thanks for checking Falk!  This is a known issue because we only processed region 18 for this update. It includes most of the CA rivers but not all, especially around Lake Tahoe. In the next version we will include all the comids. I think your extraction scripts are probably fine.

**Comment by postfalk** [comment]
No problem. It would not be a problem to do the three regions separately.

**Comment by postfalk** [comment]
New data does not seem to have estimated median data. Is that correct?

**Comment by kklausmeyer** [comment]
Good catch!  That is an oversite on my part.  I'll go back and check the code to add median back in.  But for this version (2.1.0) lets just go with min, max, and mean, since those are the ones most people use anyway.  We will bring median back in in the next version.

**Comment by postfalk** [comment]
Ok. How will we deal with inconsistency? Will we remove the median button for now and change the code for the streaming such that median will not be used?

**Comment by kklausmeyer** [comment]
The median data will still be available for the 1950-2015 data, so I don't think any changes to the UI will be needed.  I can make a note in the changelog that indicates the median data are not included in the 2016-2021 data.

**Comment by postfalk** [comment]
Thx

**Comment by postfalk** [comment]
@kklausmeyer The data is up in its incomplete form. What are the next steps in terms of integrating with the frontend? Please create issues! Thank you, Falk

**Comment by kklausmeyer** [comment]
Hi @postfalk -  I tested a download of the 2016-2021 data with the following call to the API:

https://flow-api.codefornature.org/v2/stream/?comids=10000042&begin_year=2016&end_year=2021

It returns an empty table.  Do I need to modify the api call?  How else can I verify that the data are available?

**Comment by kklausmeyer** [comment]
Issues 204-209 in this repo are all designed to update the front end with the new post-2016 data:
https://github.com/tnc-ca-geo/flow-interface/issues
