### ISSUE TITLE
Update default end_year

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/rivers-stream#71]
Hey @postfalk, it looks like the default is still `2015`, so if you do not include the `end_year=2021` query param in the request, you just get data back from 1950 - 2015. 

e.g., w/o `end_year`:
https://flow-api.codefornature.org/v2/stream/?variables=estimated,p10,p90,observed&begin_year=1950&statistics=mean&comids=15030099

and w/ `end_year=2021`: 
https://flow-api.codefornature.org/v2/stream/?variables=estimated,p10,p90,observed&begin_year=1950&end_year=2021&statistics=mean&comids=15030099

**Comment by nathanielrindlaub** [comment]
Hey @postfalk - the end year should now be bumped to 2022 (see https://github.com/tnc-ca-geo/flow-interface/issues/214).

**Comment by postfalk** [comment]
Is this still the case. I tested today and I either did not encounter or don't understand the problem. @nathanielrindlaub Please provide example query. Thank you

**Comment by postfalk** [comment]
Otherwise, pls close out. Thx

**Comment by kklausmeyer** [comment]
Hi @postfalk -  I was able to replicate this problem.  Basically the default value for the "end_year" parameter seems to be 2015, but it should be the current year (eg., 2022).  When I query the api with this URL:

[https://flow-api.codefornature.org/v2/stream/?comids=15039097,2803945&statistics=mean,max&begin_year=1980&months=1,3,5](https://flow-api.codefornature.org/v2/stream/?comids=15039097,2803945&statistics=mean,max&begin_year=1980&months=1,3,5)

I get a csv file, and the maximum value of the data in the "year" column is 2015.  It should be 2022.  See if you get the same behavior.

**Comment by postfalk** [comment]
Thank you. That is helpful. Falk

**Comment by postfalk** [comment]
Done at least to the beginning of 2023

**Comment by kklausmeyer** [comment]
Looks good- thanks @postfalk !
