### ISSUE TITLE
Publish latest monthly data to API

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#72]
Hi @postfalk - I have run the "MVP" code to generate monthly flow estimates for all COMIDs and observed flow summaries for COMIDs with gages for two additional months.   I'd like you to publish the data for October, November, and December, 2021.  The data are available here:

"N:\Projects\CA_FWA\projects\UnimparedFlows\data\modeled_and_observed_flow\flow_2021_10.csv"
"N:\Projects\CA_FWA\projects\UnimparedFlows\data\modeled_and_observed_flow\flow_2021_11.csv"
"N:\Projects\CA_FWA\projects\UnimparedFlows\data\modeled_and_observed_flow\flow_2021_12.csv"

As with issue #70 , the schema is the same as the existing database, but the number of COMIDs is smaller (only available for processing unit 18) and the median modeled data is missing.  Let me know if you have any questions!

**Comment by kklausmeyer** [comment]
Updated the request to include December 2021 data- hot off the presses!

**Comment by postfalk** [comment]
I think you added p50 which is the mean likely hood of the the prediction but I think what we are missing compared to the older data is the predicted mean.

**Comment by kklausmeyer** [comment]
Ahh yes good catch.  I think you are right.  One version of the original data from USGS did include p50 estimates and one did not.  It looks like we did not upload p50 for the API.  "Estimated" is the mean of the model predictions, and that is included in the data files linked above.  Are you able to filter out the p50 data, or do you want me to do it?

**Comment by postfalk** [comment]
I can do it no problem

**Comment by postfalk** [comment]
Please review new data.

**Comment by kklausmeyer** [comment]
Initial spot check look great-  thanks @postfalk !  I will close for now and will create a new issue if I spot any problems.
