### ISSUE TITLE
Publish latest monthly data to API

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#75]
Hi @postfalk I have completed the flow estimates for January and February of 2022.  Please upload these to the natural flows database.  The instructions are similar to issues #72 and #70.  The data are on the N drive and on box- feel free to use either location:

Jan 2022:  "N:\Projects\CA_FWA\projects\UnimparedFlows\data\modeled_and_observed_flow\flow_2022_01.csv". Box [link.](https://tnc.box.com/s/mc1uwpszy81r7jfqt9d1k5nbnc9dtpxy)
Feb 2022: "N:\Projects\CA_FWA\projects\UnimparedFlows\data\modeled_and_observed_flow\flow_2022_02.csv". Box [link](https://tnc.box.com/s/ht5io911iqsk34k255jm46a7r7menjop).

**Comment by postfalk** [comment]
Should be online and working. Please check and close. Thx

**Comment by kklausmeyer** [comment]
Spot checking looks good- thanks Falk!
