### ISSUE TITLE
Publish v2.1.1 data to API including March and April 2022.

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#76]
Hi @postfalk - I have updated the MVP flow update code to version 2.1.1.  This update includes the median flow estimates as well as the missing comids from vpu 15, 16, and 17.  Now the 2016 and later data should be the same as the 2015 and earlier data.  I have also included March and April 2022 flow estimates. 

I have zipped all the data and posted it to [box](https://tnc.box.com/s/vrxyoa4ufkf0ai8cpn4u13nzysbrpqw3).  The csvs are over 6GB unzipped, and 1.3 GB zipped.

Note, these data files include all of the data that was already uploaded, as well as the new data.  I don't know what is easier for you, but you can delete all existing data with year >= 2016 and replace with these data.  Because I have added in the new "median" flow estimates, all COMIDs need to be updated.

As always, let me know how I can help and if you have any questions.

**Comment by postfalk** [comment]
I am picking this up now and hope to be done by the end of next week.

**Comment by kklausmeyer** [comment]
Great news- thanks @postfalk

**Comment by postfalk** [comment]
This overwhelmed my scripts, I have to rethink the structure. I still hope to close this out by the end of the week.

**Comment by postfalk** [comment]
Finally done, feel free to send May along. Falk

**Comment by kklausmeyer** [comment]
Initial spot check looks great-  thanks @postfalk !
