### ISSUE TITLE
Publish June 2022 data to API

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#80]
Hi @postfalk - the latest data is ready to be uploaded to the API-

Here is the link:  
https://tnc.box.com/s/324idtqfcgvhsw7wjm7fyndtewpshnwd

Let me know if you have any questions!

Kirk

**Comment by postfalk** [comment]
Thank you, will do.


Falk Schuetzenmeister | Engineering Lead | Conservation Technology

The Nature Conservancy

t. 510.604.8010





________________________________
From: Kirk Klausmeyer ***@***.***>
Sent: Thursday, July 14, 2022 2:28 PM
To: tnc-ca-geo/rivers-stream ***@***.***>
Cc: Falk Schuetzenmeister ***@***.***>; Assign ***@***.***>
Subject: [tnc-ca-geo/rivers-stream] Publish June 2022 data to API (Issue #80)


Hi @postfalk<https://github.com/postfalk> - the latest data is ready to be uploaded to the API-

Here is the link:
https://tnc.box.com/s/324idtqfcgvhsw7wjm7fyndtewpshnwd<https://tnc.box.com/s/324idtqfcgvhsw7wjm7fyndtewpshnwd>

Let me know if you have any questions!

Kirk

**Comment by postfalk** [comment]
Ready for review and spot checking.

**Comment by kklausmeyer** [comment]
Thank you @postfalk !  Spot checking looks good!
