### ISSUE TITLE
API is serving an older version of the FFM alteration data

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#81]
Hi @postfalk - it looks like the current data on the API is serving out-of-date observed functional flow metric data.  We had several rounds of updates to these data, so I'm not surprised that you didn't grab the latest one in the latest update.  Basically, issue #69 has the instructions and link to the latest observed data on Box, in a file named "ffm_observed_20210326.csv".  The version of observed data you have online now is missing the "observed_year_start" and "observed_year_end" fields, so the alteration data is showing up in the "observed_year_start" field.  See screenshot below:

![image](https://user-images.githubusercontent.com/11560493/181081077-e288a848-b4e2-43d5-a9c3-e3f9ab9a9d8c.png)

If you follow up update steps in #69 it should fix the problem.  Thanks for your help on this!

**Comment by postfalk** [comment]
Oh no. I think we did not update the data download link and I deleted the latest version. Will fix asap.

Falk


Falk Schuetzenmeister | Engineering Lead | Conservation Technology

The Nature Conservancy

t. 510.604.8010





________________________________
From: Kirk Klausmeyer ***@***.***>
Sent: Tuesday, July 26, 2022 11:15 AM
To: tnc-ca-geo/rivers-stream ***@***.***>
Cc: Falk Schuetzenmeister ***@***.***>; Assign ***@***.***>
Subject: [tnc-ca-geo/rivers-stream] API is serving an older version of the FFM alteration data (Issue #81)


Hi @postfalk<https://github.com/postfalk> - it looks like the current data on the API is serving out-of-date observed functional flow metric data. We had several rounds of updates to these data, so I'm not surprised that you didn't grab the latest one in the latest update. Basically, issue #69<https://github.com/tnc-ca-geo/rivers-stream/issues/69> has the instructions and link to the latest observed data on Box, in a file named "ffm_observed_20210326.csv". The version of observed data you have online now is missing the "observed_year_start" and "observed_year_end" fields, so the alteration data is showing up in the "observed_year_start" field. See screenshot below:

[image]<https://user-images.githubusercontent.com/11560493/181081077-e288a848-b4e2-43d5-a9c3-e3f9ab9a9d8c.png>

If you follow up update steps in #69<https://github.com/tnc-ca-geo/rivers-stream/issues/69> it should fix the problem. Thanks for your help on this!
