### ISSUE TITLE
Update link to data source

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#82]
The link below does not point to the most recent version, which is on the server. Please point to 

https://rivers.codefornature.org/data/ffm-final-v1.2.1.zip

<img width="1024" alt="Screen Shot 2022-07-26 at 5 01 00 PM" src="https://user-images.githubusercontent.com/2914535/181132628-43050e27-3251-453d-ac0a-bf10d65985b2.png">

**Comment by postfalk** [comment]
Done

**Comment by kklausmeyer** [comment]
@postfalk - I don't see this change live on https://rivers.codefornature.org/#/data.  Did you push the changes live?

**Comment by postfalk** [comment]
Which link do you refer to. Or is it missing altogether. Thx

**Comment by kklausmeyer** [comment]
When I load the data page- I see:
![image](https://user-images.githubusercontent.com/11560493/192062250-fdedabc7-951b-4e39-8fd4-35d4abc99563.png)

The highlighted link in the image links to: https://rivers.codefornature.org/data/functional_flows_data.zip.  
But it should link to: https://rivers.codefornature.org/data/ffm-final-v1.2.1.zip.  

Can you make that switch?  Or am I just looking at an older cached version of the site?

**Comment by postfalk** [comment]
You certainly are not I see the same thing. I wonder whether Natty made his changes of an un-merged branch @nathanielrindlaub Could you please check?

**Comment by postfalk** [comment]
Yeah. That is my fault. He edited an unmerged version BUT I am the person who did not merge. Sorry

**Comment by postfalk** [comment]
Solved. Sorry for my confusion

**Comment by kklausmeyer** [comment]
Great- I can see the changes now- thank you!
