### ISSUE TITLE
Upload September 2022 data

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#90]
Hi @postfalk can you upload these data to the natural flows database?  Format and schema should be the same:

Sept 2022:  https://tnc.box.com/s/j0yz7lc3czyddt8n6vgz7h5jk42cto5n 

Thank you!

Kirk

**Comment by postfalk** [comment]
Ready for review and closure. Falk

**Comment by kklausmeyer** [comment]
Spot checks look good- thank you @postfalk !
