### ISSUE TITLE
Upload October 2022 Data

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#91]
Hi Falk!  Another update request!  Can you upload the October 2022 data to the natural flows database?  Thank you!

Here is the link to the data:

https://tnc.box.com/s/u1q8o69rqip0q08p9k473e3ybxwaesz6

**Comment by postfalk** [comment]
I am on it!

**Comment by postfalk** [comment]
Up for evaluation. Please check!

**Comment by kklausmeyer** [comment]
Looks good- thank you Falk!
