### ISSUE TITLE
Upload November 2022 Data

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#92]
Hi Falk-  that time of the month again!  

Here is the data to upload to the natural flows database:
https://tnc.box.com/s/1bgyijy92uxi1kbirk7iqxi5kcs7hk9e  

Let me know if you have any issues-

Kirk

**Comment by postfalk** [comment]
Up for testing and evaluation. Pls test ffm as well.

**Comment by kklausmeyer** [comment]
Initial spot checks look good.  Did you make changes to the ffm metrics too?  They all seem fine to me.

**Comment by postfalk** [comment]
No, I did not. I just moved it into a different space since I had to copy and relink it every time in the past. Not it is independent from the other data. Just to make sure it is linked correctly.
