### ISSUE TITLE
Upload January 2023 data

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#94]
Hi Falk-  can you upload the Jan 2023 data, available here:

https://tnc.box.com/s/gsvbzje5dzdkqpxkcw46ofnqmcyly09a

In addition, can you update the default settings on the API to reflect 2023 as the end year for data downloads.  Here are the places that need updates:

https://rivers.codefornature.org/#/data
"begin_year (integer): one value between 1950 .. 2022 (default: 1950)
end_year (integer): one value between 1950 .. 2022 (default: 2022)"

https://rivers.codefornature.org/#/map
In the right hand sidebar, there are options to download the data- set the default end year to 2023
"Years From: 1950 To: 2022"

Multiple pages-

When using the monthly data please use the following citation:
Julie K.H. Zimmerman, Daren M. Carlisle, Jason T. May, Kirk R. Klausmeyer, Theodore E. Grantham, Larry R. Brown, Jeanette K. Howard. California Unimpaired Flows Database v2.1.1, 2022. The Nature Conservancy. San Francisco CA. https://rivers.codefornature.org/ (Date Accessed)

Change the publication data from 2022 to 2023.

Thanks!

**Comment by postfalk** [comment]
@kklausmeyer Please evaluate data and content changes on https://rivers-staging.codefornature.org/#/map.

**Comment by kklausmeyer** [comment]
Looks great to me- thanks Falk!
