### ISSUE TITLE
Update data to Version 2.1.2

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#95]
Hi Falk-

I have fixed the error in my processing pipeline and recalculated all the modeled flows from April 2022 to February 2023.  Please find the updated data arranged by month here on box:  https://tnc.box.com/s/x987phyibkrvp6vil4cudr4x4977fn9x

The changes affect about 15,000 comids.  I'm thinking it will be easiest to delete all the data in the cloud database from April 2022 to February 2023, and then replace with these new data.

I talked with Matt about some options for version control, and here are some options we could do:
1. Publish the new data and delete the old version (version 2.1.1).  This isn't ideal because people won't be able to re-create any data summaries they created with v2.1.1
2. Keep a copy of v2.1.1 as an archive, similar to what we have done with GDE Pulse.  This also isn't ideal because we have to host and maintain the old version, and I don't think that many people will actually use it.
3. Publish the new data along with a file that lists all the comids that changed, and the v2.1.1 modeled flow and the v2.1.2 modeled flow.  I am leaning toward this option because it provides a record of v2.1.1 but does it in a light weight manner in terms of hosting.  I have create the change file here:  https://tnc.box.com/s/zcrx6x0s4onlqvhsfbioxkloy8i8d9h3

Matt wants to keep some record of the older data as well, so he would vote for options 2 or 3.  Let me know what you think!

**Comment by postfalk** [comment]
@kklausmeyer Would you like to do 2 if feasible or did you already decide that 3 is the best option? Not sure whether there is a question in there.

**Comment by postfalk** [comment]
@kklausmeyer time step 05/2022 seems to be missing im the updated data

**Comment by kklausmeyer** [comment]
Good question-  I think we should go for option 3 unless you have a strong opinion on the matter.

**Comment by kklausmeyer** [comment]
Thanks for double checking the data!  I uploaded 05/2022 to box.  You can find it here:

https://tnc.box.com/s/r7wj6q7td1u0zbhic2ehuco3dy5plafo

**Comment by kklausmeyer** [comment]
Hi Falk-  not sure if it is too late, but I just completed the predicted flows for March 2023:

https://tnc.box.com/s/3o9rlx1fdz86zfw67k8wttjjnjrhw145

The validation numbers are better than Feb 2023 so that is good.  

I can add this to a new issue if you prefer.

**Comment by postfalk** [comment]
No that is actually good. Falling behind. Will work on this after next week (I will be on vacation).

**Comment by kklausmeyer** [comment]
Spot check complete and everything looks good.  Feel free to close this issue out.
